### ISSUE TITLE
Ecrire aux parents et aux élèves

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/publipostage#12]
Implémenter un nouveau canal de diffusion d'information à destination des parents et élèves (anvciennement appelé "info-famille") dans Laclasse v2. Le nom de ce canal reste à définir.
L'entrée du back-office se fait par les pavés "écrire aux parents" et "ecrire aux élèves".

Ce nouveau flux sera
 - stocké dans la base annuaire (avec le référentiel publipostage)
 - aux normes RSS, pour être consommé par le portail, fusionnés avec d'autres flux internes ou externes.

**Comment by SamSuffit** [comment]
see laclasse-com/service-annuaire/issues/#36
