### ISSUE TITLE
Doublons dans la liste des classes

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/publipostage#16]
Avec un profil Super ADmin, la liste des classes comporte plein de doublons qu'il fauadrait filtrer.
De fait, lorsqu'on revient en arrière après avoir choisi une classe ("changer les destinataires") la liste des classes choisies est pleine de doublons : 

![ercire-famille1](https://cloud.githubusercontent.com/assets/1265220/6728134/bfeb0bfe-ce27-11e4-843c-e8f8e9bd864d.png)

![ecrire-famille-doublons](https://cloud.githubusercontent.com/assets/1265220/6728156/f4aa81d0-ce27-11e4-8976-a8550202dec9.png)

**Comment by hquenin** [comment]
je n'arrive pas à reproduire l'erreur 
je n'arrive pas non plus à me mettre administrateur etab sur val d'argent sur l'admin panel

**Comment by Pilooz** [comment]
Je ne reproduis plus non plus sur la dev, il est possible que les travaux sur l'annuaire qui datent d'il y a 4 -5 mois et livrés ces temps-ci aient corrigé le pb.
