### ISSUE TITLE
Champs non interprétés, champs dont l'affichage est erroné

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/publipostage#18]
## Champs non interprétés
- signature ( => Générer la signature de l'auteur du publipostage : Prénom, Nom, et à la ligne établissement)

## Champs dont l'affichage est erroné
- Civilité est en majuscule ( => afficher M., Mme, Mlle)
- adresse : n'affiche ni le code postale ni la ville (Faut-il ajouter des champs cp et ville ?)
- Lien "Laclasse" (=> Renommer "Lien ENT", afficher le lien en entier)

**Comment by hquenin** [comment]
comment fait on pour génerer une signature ?

**Comment by Pilooz** [comment]
Générer la signature de l'auteur du publipostage : 


Prénom  Nom (de l'auteur du publipostage)
Fonction dans l'établissement
Nom de l'établissement

**Comment by hquenin** [comment]
pour la civilité c'est celle du current user ou on affiche les trois civilités possible ?

**Comment by Pilooz** [comment]
Si tu parles de la civilité dans le message texte, il s'agit biensûr de celle du destinataire. dans la signature, parcontre il n'y a pas de civilité.

**Comment by hquenin** [comment]
je parle de la civilité dans les messages textes que tu peux insérer.
quand il y a plusieurs classe, ou plusieurs personnes je met quoi

**Comment by Pilooz** [comment]
En fait le message que tu es en train d'écrire, est un modèle de message qui va être fusionné avec les données de la bases. Tu mettras donc bien la civilité de chacun des élèves de chaque classe sélectionnée, ça pas de problème.
Pour ce qui est des familles, il y a plusieurs possibilités : 
- Soit on grise le bouton 'civilité' 
- Soit on met  _Monsieur et Madame_ en tout lettre. (embêtant pour les couples à noms différents ou divorcés)
- Soit on met explicitement Madame <nom de la mère>, Monsieur <Nom du père>,

Quel est ton avis sur cette question @cycojesus ?

**Comment by Pilooz** [comment]
En fait, on va mettre explicitement les civilité des 2 parents avec leurs noms. ex : 
le modèle `[civilité] [nom] ` lorsqu'on est dans _"Ecrire aux familles"_ doit être interprété comme suit : 
```
Madame Trucmuche,
Monsieur Machin,
```
En prime, ci dessous un texte à saisir dans l'application pour vérifier que tous les champs sont bien interprétés
```
[civilite] [nom] [prenom]

adresse = [adresse]

date = [date]

signature =[signature]

nomElv = [nomEleve]

prenElv = [prenomEleve]

classe = [classe]

blog etab = [blogEtab]

blog classe = [blogRegroupement]

lien ent : Laclasse
```

**Comment by hquenin** [comment]
j'ai compris pour la civilité 
mais pour le texte c'est juste que je dois faire un test c'est ça ?

**Comment by Pilooz** [comment]
Avec le texte ci-dessus ? Je l'ai écrit pour tester que tous les champs sonft bien interprétés dans le traitement, du coup je peux le ré-utiliser.
Il est possible qu'il faille que tu complètes les tests unitaires aussi.
