### ISSUE TITLE
erreur mysql sur écrire aux profs

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/publipostage#19]
Contexte :  champs de fusion + diffusion pdf.
pas de choix de matière.

Une erreur s'est produite: Une erreur s'est produite: { Code: 400 Erreur: {"error"=>"undefined method `empty?' for -1:Fixnum"} }

verifiez les requêtes au serveur des Apis

**Comment by hquenin** [comment]
je ne comprends pas exactement comment reproduire l'erreur
