### ISSUE TITLE
Export des mots de passe dans un fichier csv ou excel

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/publipostage#27]
Possibilité d'exporter un fichier en CSV ou EXCEL par les profils d'admin d'un établissement pour que l'établissement récupère les identifiants et mots de passe automatiques des comptes, pour chaque profil (en indiquant aussi pour les comptes parents, le lien entre nom+prénom+classe de l'élève et du parent) et les transmette à ses utilisateurs en début d'année (via un publipostage réalisé par l'établissement sans avoir recours à l'outil de publipostage de Laclasse.com pour que l'établissement puisse avoir la main complètement sur le texte et les documents joints du publipostage selon les outils utilisés dans l'établissement et les accès ouverts à chaque profil sur ces outils)

**Comment by Pilooz** [comment]
Fonctionnalité plus nécéssaire, si le publipostage des mots de passe fonctionne.
